# The site blueprint must have a title, the title may be different from the file name
# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
title: Site

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:
tabs:
  sitePages:
    label: Pages
    icon: page
    columns:
      # The first column has one section for the subpages of the `photography` page in card layout
      # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
                     
      - width: 1/2
        sections:
          onseason: sections/en-saison
          pages:
            type: pages
            create: default
            templates:
              - home
              - about
              - infos
              - ateliers
              - espace-pro
              - default
      - width: 1/2
        sections:
          archivesPages: sections/archives
          archives:
            type: fields
            fields:
              pdfArchives:
                label: Archives PDF – Spectacles
                type: structure
                help: Télécharger ici les anciens programmes de saisons**
                fields:
                  title:
                    type: text
                    label: Nom du document
                    width: 1/2
                  doc:
                    label: Document
                    type: files
                    template: document
                    query: page.files.filterBy('template', 'document')
                    width: 1/2
              adventuresArchives:
                label: Archives PDF – Aventures à partager
                type: structure
                help: '**'
                fields:
                  title:
                    type: text
                    label: Nom du document
                    width: 1/2
                  doc:
                    label: Document
                    type: files
                    template: document
                    query: page.files.filterBy('template', 'document')
                    width: 1/2
              artistsArchives:
                label: Archives PDF – Artises en résidence 
                type: structure
                help: '**'
                fields:
                  title:
                    type: text
                    label: Nom du document
                    width: 1/2
                  doc:
                    label: Document
                    type: files
                    template: document
                    query: page.files.filterBy('template', 'document')
                    width: 1/2
              archivesInfos:
                label: Basculer une saison en Archive – Process
                type: info
                text:|
                  Dupliquer la page **Spectacles et Évènements** de la saison en cours

                  Renommer le mot 'copier' de l'url en l'année de la saison 
                  (Ex -> spectacles-copier devient spectacles-20202021)

                  Copier les fichiers et les pages (Tout basculer sur ON)

                  Changer le titre 'Spectacles' en **Archive XXXX-XXXX**

                  Basculer le statut de **Brouillon** à **Non Listé**

                  Compléter la section **En saison** avec les spectacles correspondants

                  -> Idem pour **Aventures à partager** et **Artistes en Résidence**

                  Et voilà !
  sitePiles:
    label: Fiches
    icon: file
    columns:
       - width: 1/3
        sections:
          spectacles: 
            extends: sections/spectacles
            status: listed
            #help: "Définir l'ordre des spectacles dans la Page Spectacle"
       - width: 1/3
        sections:
          ateliers: 
            extends: sections/aventures
            status: listed
            #help: "Définir l'ordre des ateliers dans la Page Atelier"
       - width: 1/3
        sections:
          aventures: 
            extends: sections/ateliers
            status: listed
            #help: "Définir l'ordre des aventures dans la Page Aventures"   
  
  artists:
    icon: smile
    label: Artistes et intervenants
    columns:
       - width: 1/2
        sections:
          artistes: sections/artistes
       - width: 1/2
        sections:
          intervenants: sections/intervenants

  globalInfos:
    icon: page
    label: Informations générales
    columns:
      - width: 1/1
          sections:
            content:
              type: fields
              fields:
                description:
                  label: Description générale du site
                  type: writer
                  width: 1/2
                mainImage:
                  label: Logo Principal
                  type: files
                  template: image
                  uploads:
                  template: image
                  width: 1/2
                hr:
                  type: line
                address:
                  label: Adresse
                  type: writer
                  inline: true
                  width: 1/2
                email:
                  label: Email de contact
                  type: email
                  width: 1/4
                mainphone:
                  label: Téléphone de l'accueil
                  type: tel
                  width: 1/4
                ticketingphone:
                  label: Téléphone de la billetterie
                  type: tel
                  width: 1/4
                ticketing:
                  label: Lien vers la billetterie
                  type: url
                  width: 1/4
                social:
                  label: Sur les réseaux
                  type: structure
                  fields:
                    platform:
                      label: Réseau
                      type: text
                      width: 1/2
                    url:
                      label: URL
                      type: url
                      width: 1/2




          

